### ISSUE TITLE
Speaker anfragen

### ISSUE THREAD

**Issue by webwurst** [codeformuenster/codeformuenster#20]
- [ ] [Marc Tobias Metten](http://www.openstreetmap.org/user/mtmail), [Twitter](https://twitter.com/mtmthemovie)
- [ ] Freifunk / Lorawan
- [ ] [OpenStreetMap](http://wiki.openstreetmap.org/wiki/M%C3%BCnster)
- [x] [Wir in Kinderhaus](http://www.gutes-morgen.ms/de/wir-in-kinderhaus/) => Gleiche Personen wie "Mach mit, Münster"
- [x] [MünsterWiki](http://wiki.muenster.org/index.php/Hauptseite)
- [x] [Mach mit, Münster](http://www.mach-mit-muenster.de/) => Thomas hat ihnen eine Mail gesendet
- [ ] Repair Cafe Leute fragen

Absagen
- [x] Tobias Pfaff => hat keine Zeit

**Comment by ubergesundheit** [comment]
Schreibe Mail an Tobias Pfaff
