### ISSUE TITLE
Leute einladen

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/codeformuenster#23]
* Gerald hat die Freifunker wieder eingeladen über ihr Forum
* [x] Mach Mit Münster - Haben zugesagt, kommen gerne vorbei
* [x] Münster Wiki Leute - kommt (Mail an wiki at muenster.org ging raus 31.1.) keine Antwort, aber @jahnique kennt jemand dort und fragt mal
* [x] Tom schreibt noch diese Woche was über den PresseVerteiler 
  * 3 PolitikerInnen haben zugesagt, es wird auch ein Grußwort geben.
* Schattenskulptur Interessierte?
 => Schanze Verein
 => [x] B-Side => kommt = Tom und Jochen waren bei deren Treffen und sie finden es gut, und wir treffen uns nochmal mit ihnen um Details zu planen
* repair cafe leute sind eingeladen

**Comment by jahnique** [comment]
Antwort MünsterWiki (Ulrich Kathöfer):

> Lieber Herr Schencking, 
> 
> neee, die Mail ging nicht ins Leere, wir reagieren nur seeeehr langsam. 
> Es wird sich wohl Klaus-Otto Nagorsnik melden, der nicht nur alles weiß, 
> weil er alle Bücher der Stadtbücherei gelesen hat, sondern auch Google 
> und Wikipedia bedienen kann. Und der Europameister in Stadt-Land-Fluss 
> und Jäger im Fernsehen ist. ;-) 
> 
> Ich glaube, er mag auch Pizza ... 
> 
> Ansonsten: Sieht man sich vielleicht bei der Stallman-Veranstaltung 
> nächste Woche? 
> 
> Schöne Grüße 
> -uk
