### ISSUE TITLE
Plakate drucken

### ISSUE THREAD

**Issue by webwurst** [codeformuenster/codeformuenster#3]
- [ ] Plakat updaten (https://github.com/codeformuenster/opendataday/blob/poste/odd15_poster.svg)
- [ ] Plakatsponsor finden #4
- [ ] Plakat drucken

**Comment by chk1** [comment]
Poster als svg-Datei ist hier: https://github.com/codeformuenster/opendataday/blob/poster2016/odd16_poster.svg

**Comment by ubergesundheit** [comment]
Müssen noch klären ob con terra und wn wieder dabei sind -> "Medienpartner"

**Comment by ubergesundheit** [comment]
Wegweiser waren gedruckt!
