### ISSUE TITLE
Plakate mit Anküngigung

### ISSUE THREAD

**Issue by webwurst** [codeformuenster/codeformuenster#37]
- [x] Plakat entwerfen @ubergesundheit 
- [x] Entwurf überarbeiten
- [x] in `PDF` wandeln
- [x] drucken @AstridReich 
- [x] verteilen

**Comment by ubergesundheit** [comment]
Vorläufiges Plakat ist hier:
https://github.com/codeformuenster/opendataday/blob/gh-pages/odd18_poster.svg
Link zur Schriftart steht in der Datei

**Comment by tomsrocket** [comment]
Hier ist die finale Version: https://github.com/codeformuenster/opendataday/blob/gh-pages/poster/odd18_poster.pdf
