### ISSUE TITLE
Mittagessen organisieren

### ISSUE THREAD

**Issue by webwurst** [codeformuenster/codeformuenster#38]
Finanzierung:
- [x] [OKFN mini-grant scheme](https://blog.okfn.org/2018/01/22/announcing-the-open-data-day-2018-mini-grants-scheme/) anfragen.
  > selected grantees will be announced on Monday, 19th February 2018
  -> `nope`
- [x] Alternative?
  Es gibt einen Geldtopf von OKFDE

Pizza-Dienst:
- [x] Auswählen
  [Gators](https://www.gators-pizza.de/)?

--- 
Gators geht klar, am besten abends zuvor noch einmal anmelden.
Dann am Samstag um 11:30/12:00 Uhr nochmal.
Geld erstmal vorstrecken.

**Comment by ubergesundheit** [comment]
Habe uns beim OKFN mini-grant scheme angemeldet (https://blog.okfn.org/2018/01/22/announcing-the-open-data-day-2018-mini-grants-scheme/) und bei Sarina wegen Pizza-Geld nachgefragt schon.

Weiß einer von euch noch bei welchem Pizza-Dienst wir die letzten Jahre bestellt haben? @webwurst @tomsrocket
